# Generated by Django 4.2.7 on 2023-11-17 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_clients'),
    ]

    operations = [
        migrations.RenameField(
            model_name='clients',
            old_name='fullname',
            new_name='name',
        ),
        migrations.AddField(
            model_name='clients',
            name='age',
            field=models.CharField(default='10', max_length=5),
        ),
        migrations.AddField(
            model_name='clients',
            name='sex',
            field=models.CharField(default='male', max_length=5),
        ),
        migrations.AlterField(
            model_name='clients',
            name='client_id',
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name='clients',
            name='mobile',
            field=models.CharField(default='', max_length=15),
        ),
    ]
